//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurat_soft
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public decimal SALARIO { get; set; }
        public string categoria { get; set; }
    }
}
